// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADLOW7ZcQde--XnOQisF-L-Eetmu4IwLg',
    appId: '1:798524739892:web:2c87b1f60f35376bb39561',
    messagingSenderId: '798524739892',
    projectId: 'car-wash-proj',
    authDomain: 'car-wash-proj.firebaseapp.com',
    storageBucket: 'car-wash-proj.firebasestorage.app',
    measurementId: 'G-3R9S2FEMYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoiHW6uy9L_7E3eNplVYwqA_PwxByk8k4',
    appId: '1:798524739892:android:dd16f6df141277cab39561',
    messagingSenderId: '798524739892',
    projectId: 'car-wash-proj',
    storageBucket: 'car-wash-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrGRmJkeXCxZ2JvI3WTIlcuy3gSeTU7Zw',
    appId: '1:798524739892:ios:f39bc05944895a18b39561',
    messagingSenderId: '798524739892',
    projectId: 'car-wash-proj',
    storageBucket: 'car-wash-proj.firebasestorage.app',
    iosBundleId: 'com.example.carWashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrGRmJkeXCxZ2JvI3WTIlcuy3gSeTU7Zw',
    appId: '1:798524739892:ios:f39bc05944895a18b39561',
    messagingSenderId: '798524739892',
    projectId: 'car-wash-proj',
    storageBucket: 'car-wash-proj.firebasestorage.app',
    iosBundleId: 'com.example.carWashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADLOW7ZcQde--XnOQisF-L-Eetmu4IwLg',
    appId: '1:798524739892:web:a2987258ff95c151b39561',
    messagingSenderId: '798524739892',
    projectId: 'car-wash-proj',
    authDomain: 'car-wash-proj.firebaseapp.com',
    storageBucket: 'car-wash-proj.firebasestorage.app',
    measurementId: 'G-T4LV8V37ZS',
  );
}
